### ISSUE TITLE
Upgrade DAVL to Daml-LF 1.8 or newer

### ISSUE THREAD

**Issue by cocreature** [digital-asset/davl#315]
SDK 2.0 will drop support for Daml-LF 1.8 in damlc and in daml2js. If we want to keep it in the release checklist we need to upgrade it.

**Comment by garyverhaegen-da** [comment]
Is that going to require an explicit upgrade with permission from everyone?

**Comment by stefanobaghino-da** [comment]
The main reason why we maintained DAVL so far has been to use it as a test for upgrades. Given that now we have much more telling use cases that perform smoke tests for us (Daml Hub in particular), we decided to not work actively on DAVL. As such, for the time being we'll "let it be" and possibly do the active work of discontinuing it completely at some point in the future.
